{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "schema-registry.fullname" . }}
  labels:
    {{- include "schema-registry.labels" . | nindent 4 }}
    app.kubernetes.io/component: availability
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "schema-registry.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: server
  unhealthyPodEvictionPolicy: IfHealthyBudget
{{- end }}
