apiVersion: v1
kind: Service
metadata:
  name: {{ include "schema-registry.fullname" . }}
  labels:
    {{- include "schema-registry.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.sessionAffinity }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  {{- end }}
  selector:
    {{- include "schema-registry.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
  ports:
    - name: http
      port: {{ .Values.service.http.port }}
      targetPort: http
      protocol: TCP
    - name: grpc
      port: {{ .Values.service.grpc.port }}
      targetPort: grpc
      protocol: TCP
---
{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "schema-registry.fullname" . }}-metrics
  labels:
    {{- include "schema-registry.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
spec:
  type: ClusterIP
  selector:
    {{- include "schema-registry.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
  ports:
    - name: metrics
      port: {{ .Values.service.metrics.port }}
      targetPort: metrics
      protocol: TCP
{{- end }}
