apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: schema-registry

commonLabels:
  app.kubernetes.io/name: schema-registry
  app.kubernetes.io/managed-by: kustomize

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - pdb.yaml
  - ingress.yaml
  - networkpolicy.yaml
  - postgres-statefulset.yaml
  - redis-statefulset.yaml

images:
  - name: schema-registry
    newName: ghcr.io/llm-schema-registry/schema-registry
    newTag: latest
