apiVersion: v1
kind: ServiceAccount
metadata:
  name: schema-registry
  namespace: schema-registry
  labels:
    app.kubernetes.io/name: schema-registry
    app.kubernetes.io/component: serviceaccount
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: schema-registry-role
  namespace: schema-registry
  labels:
    app.kubernetes.io/name: schema-registry
    app.kubernetes.io/component: rbac
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: schema-registry-rolebinding
  namespace: schema-registry
  labels:
    app.kubernetes.io/name: schema-registry
    app.kubernetes.io/component: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: schema-registry-role
subjects:
  - kind: ServiceAccount
    name: schema-registry
    namespace: schema-registry
